# Generated by Django 4.2.23 on 2025-07-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskmodel_is_archieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='is_archieved',
            new_name='is_archived',
        ),
    ]
