# Generated by Django 4.2.23 on 2025-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_archieved_taskmodel_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
